### ISSUE TITLE
city_jis_codeからCityの名前を取得

### ISSUE THREAD

**Issue by sannomiyah** [kmdsbng/zipcode_jp#191]
city_jis_codeから都市の名前を取得したいです。
もしお手すきであれば都市名を取得できるようにしていただけるとありがたいです。

**Comment by kmdsbng** [comment]
あー、確かにそういう関数ないですね！
実装します。

```
ZipCodeJp.getCity(
  '640820', 
   function(err, city) {
     console.log(err);
     if (city != null) {
       console.log(city.city_name)
     }
   }
);
```

↑こんな感じに使える関数で認識合ってますか？

**Comment by kmdsbng** [comment]
とりあえず、現在のJSONファイルは追加しない方向で実装しようと思います。(リポジトリサイズが増えてしまうので。)

なので、city/01.json (都道府県に含まれる市区町村一覧)などをロードしてきて、一致した市区町村をそこから見つけて返す、というような実装にしようと思います。

**Comment by sannomiyah** [comment]
返信ありがとうございます。
自作した際もそのように作成していました。(サブモジュールとして使用しており、デプロイの関係上、masterに入っているととても助かります)
よろしくお願いいたします。

**Comment by kmdsbng** [comment]
https://github.com/kmdsbng/zipcode_jp/commit/d3ad0be1d7642eac106978f76d748b6e9d6ecbff

getCity()関数追加しました。
